@echo off
echo Staging changes...
git add .
echo Committing changes...
git commit -m "Refining event creation validation and fixing UI issues"
echo Pushing to DFW branch...
git push origin DFW
echo Push complete.
